version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    labels:
      - dependencies
      - actions
      - Skip Changelog
    schedule:
      interval: weekly
      day: sunday
    commit-message:
      prefix: "chore: "

  - package-ecosystem: docker
    directory: /build/docker
    labels:
      - dependencies
      - docker
    schedule:
      interval: weekly
      day: sunday
    groups:
      docker:
        patterns:
          - "*"
    commit-message:
      prefix: "chore: "

  - package-ecosystem: gomod
    directory: "/cmd/solarwinds-otel-collector"
    schedule:
      interval: weekly
      day: sunday
    allow:
      - dependency-type: "direct"
    groups:
      collector-opentelemetry:
        patterns:
        - "*opentelemetry*"
        - "*solarwinds-otel-collector*"
      collector-miscellaneous:
        exclude-patterns:
          - "*opentelemetry*"
          - "*solarwinds-otel-collector*"
    commit-message:
      prefix: "chore: "

  - package-ecosystem: gomod
    directory: "/extension/solarwindsextension"
    schedule:
      interval: weekly
      day: sunday
    allow:
      - dependency-type: "direct"
    groups:
      solarwindsextension:
        patterns:
          - "*"
    commit-message:
      prefix: "chore: "

  - package-ecosystem: gomod
    directory: "/processor/k8seventgenerationprocessor"
    schedule:
      interval: weekly
      day: sunday
    allow:
      - dependency-type: "direct"
    groups:
      k8seventgenerationprocessor:
        patterns:
          - "*"
    commit-message:
      prefix: "chore: "

  - package-ecosystem: gomod
    directories:
      - "/internal/tools"
      - "/internal/k8sconfig"
      - "/internal/e2e"
    schedule:
      interval: weekly
      day: sunday
    allow:
      - dependency-type: "direct"
    groups:
      internal:
        patterns:
          - "*"
    commit-message:
      prefix: "chore: "

  - package-ecosystem: gomod
    directory: "/receiver/swohostmetricsreceiver"
    schedule:
      interval: weekly
      day: sunday
    allow:
      - dependency-type: "direct"
    groups:
      swohostmetricsreceiver:
        patterns:
          - "*"
    commit-message:
      prefix: "chore: "

  - package-ecosystem: gomod
    directory: "/receiver/swok8sobjectsreceiver"
    schedule:
      interval: weekly
      day: sunday
    allow:
      - dependency-type: "direct"
    groups:
      swohostmetricsreceiver:
        patterns:
          - "*"
    commit-message:
      prefix: "chore: "

  - package-ecosystem: gomod
    directories:
      - "/pkg/version"
      - "/pkg/testutil"
    schedule:
      interval: weekly
      day: sunday
    allow:
      - dependency-type: "direct"
    groups:
      pkg:
        patterns:
          - "*"
    commit-message:
      prefix: "chore: "
