version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    labels:
      - dependencies
      - actions
      - Skip Changelog
    schedule:
      interval: weekly
      day: sunday
    commit-message:
      prefix: "chore: "

  - package-ecosystem: docker
    directory: /build/docker
    labels:
      - dependencies
      - docker
    schedule:
      interval: weekly
      day: sunday
    groups:
      docker:
        patterns:
          - "*"
    commit-message:
      prefix: "chore: "

  - package-ecosystem: gomod
    directories:
      - "**/*"
    schedule:
      interval: weekly
      day: sunday
    allow:
      - dependency-type: "direct"
    groups:
      opentelemetry:
        patterns:
          - "*opentelemetry*"
      security:
        applies-to: security-updates
        patterns:
          - "*"
        exclude-patterns:
          - "*opentelemetry*"
        update-types:
          - "patch"
          - "minor"
    commit-message:
      prefix: "chore: "
