version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    labels:
      - dependencies
      - actions
      - Skip Changelog
    schedule:
      interval: weekly
      day: sunday
    commit-message:
      prefix: "chore: "

  - package-ecosystem: docker
    directory: /build/docker
    labels:
      - dependencies
      - docker
    schedule:
      interval: weekly
      day: sunday
    groups:
      docker:
        patterns:
          - "*"
    commit-message:
      prefix: "chore: "

  - package-ecosystem: gomod
    directories:
      - "cmd/solarwinds-otel-collector"
    schedule:
      interval: weekly
      day: sunday
    allow:
      - dependency-type: "direct"
    groups:
      collector-opentelemetry:
        patterns:
          - "*opentelemetry*"
      collector-security:
        applies-to: security-updates
        patterns:
          - "*"
        exclude-patterns:
          - "*opentelemetry*"
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: gomod
    directories:
      - "/extension/*/"
      - "/processor/*/"
      - "/receiver/*/"
      - "/internal/*/"
      - "/pkg/*/"
    schedule:
      interval: weekly
      day: sunday
    allow:
      - dependency-type: "direct"
    groups:
      components-opentelemetry:
        patterns:
          - "*opentelemetry*"
      components-security:
        applies-to: security-updates
        patterns:
          - "*"
        exclude-patterns:
          - "*opentelemetry*"
        update-types:
          - "patch"
          - "minor"
    commit-message:
      prefix: "chore: "
