name: Docker scout cve analysis
description: Analyse CVEs with Docker Scout and push it to sarif file

inputs:
  username:
    description: Username for logging into the Docker Scout
    required: false
  token:
    description: PAT token for logging into the Docker Scout
    required: false
  tag:
    description: Image tag
    required: true

runs:
  using: composite
  steps:
    - name: Analyze for CVEs
      id: docker-scout-cves
      if: ${{ github.event_name != 'pull_request_target' }}
      uses: docker/scout-action@v1
      with:
        command: cves
        only-severities: critical,high
        image: solarwinds-otel-collector:${{ inputs.tag }}
        sarif-file: sarif-${{ inputs.tag }}.output.json
        summary: true
        exit-code: true
        write-comment: false

    - name: Save sarif file as an artifact
      if: ${{ github.event_name != 'pull_request_target' }}
      uses: actions/upload-artifact@v4
      with:
        name: sarif-${{ inputs.tag }}.output.json
        path: sarif-${{ inputs.tag }}.output.json

