name: Analyze CVEs for image

on:
  workflow_call:
    inputs:
      tags:
        description: 'A username passed from the caller workflow'
        required: true
        default: '[]'
        type: string

jobs:
  run-composite-action-in-parallel:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        argument: ${{ fromJson(inputs.tags) }}  # Convert the input string to an array
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run composite action
        uses: ./.github/actions/analyzeImageCves
        with:
          current-image: ${{ matrix.argument }}