name: Analyze CVEs for image

on:
  workflow_call:
    inputs:
      tags:
        description: 'A username passed from the caller workflow'
        required: true
        default: '[]'

jobs:
  print-username:
    runs-on: ubuntu-latest

    steps:
      - name: Print the input name to STDOUT
        run: echo The username is ${{ inputs.username }}