name: Build and Test Images

on:
  pull_request:
    branches:
      - main
      - 'release/**'

  workflow_dispatch:
  workflow_call:

env:
  DOCKERHUB_IMAGE: solarwinds/solarwinds-otel-collector

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check licenses
        run: make ci-check-licenses

  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Docker Image Tag
        id: generate-tag
        run: echo "tag=v${{ github.run_number }}-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and Test - Full Image
        run: >
          docker build . --file build/docker/Dockerfile
          --tag solarwinds-otel-collector:${{ steps.generate-tag.outputs.tag }}
          --tag solarwinds-otel-collector:latest

      - name: E2E Tests
        working-directory: internal/e2e
        run: make e2e-tests

  build_windows:
    runs-on: windows-2022
    # this job takes a long time to run (20 minutes), so run it on main and release branches to have some continuous check that build on windows 
    # still works. Also run it on workflow_dispatch to allow manual runs.
    if: github.event_name == 'workflow_call' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate docker image tag
        id: generate-tag
        run: echo "tag=v${{ github.run_number }}-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build Full
        run: |
          docker build -t solarwinds-otel-collector:${{ steps.generate-tag.outputs.tag }}-nanoserver-ltsc2022 -f build/docker/Dockerfile.Windows-2022 . 

      - name: CP assets
        run: |
          docker create --name assets solarwinds-otel-collector:${{ steps.generate-tag.outputs.tag }}-nanoserver-ltsc2022
          docker cp assets:/solarwinds-otel-collector.exe solarwinds-otel-collector.exe

      - name: Build 2019 Full
        run: |
          docker build -t solarwinds-otel-collector:${{ steps.generate-tag.outputs.tag }}-nanoserver-ltsc2019 --build-arg WINBASE=mcr.microsoft.com/windows/nanoserver:ltsc2019 -f build/docker/Dockerfile.Windows-Runtime . 

      - name: Save image
        run: |
          docker save --output solarwinds-otel-collector-windows-ltsc2022.tar solarwinds-otel-collector:${{ steps.generate-tag.outputs.tag }}-nanoserver-ltsc2022
          docker save --output solarwinds-otel-collector-windows-ltsc2019.tar solarwinds-otel-collector:${{ steps.generate-tag.outputs.tag }}-nanoserver-ltsc2019

      - uses: actions/upload-artifact@v4
        with:
          name: image
          path: |
            solarwinds-otel-collector-windows-ltsc2022.tar
            solarwinds-otel-collector-windows-ltsc2019.tar
          retention-days: 2
 
  build_k8s:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Docker Image Tag
        id: generate-tag
        run: echo "tag=v${{ github.run_number }}-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build - k8s Image
        run: >
          docker build . --file build/docker/Dockerfile.k8s
          --tag solarwinds-otel-collector:${{ steps.generate-tag.outputs.tag }}-k8s

  build_windows_k8s:
    runs-on: windows-2022
    # this job takes a long time to run (10 minutes), so run it run it on main and release branches to have some continuous check that build on windows 
    # still works. Also run it on workflow_dispatch to allow manual runs.
    if: github.event_name == 'workflow_call' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate docker image tag
        id: generate-tag
        run: echo "tag=v${{ github.run_number }}-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build K8s
        run: |
          docker build -t solarwinds-otel-collector:${{ steps.generate-tag.outputs.tag }}-nanoserver-ltsc2022-k8s -f build/docker/Dockerfile.k8s.Windows-2022 . 
          
      - name: CP assets
        run: |
          docker create --name assets-k8s solarwinds-otel-collector:${{ steps.generate-tag.outputs.tag }}-nanoserver-ltsc2022-k8s
          docker cp assets-k8s:/solarwinds-otel-collector.exe solarwinds-otel-collector.exe
          docker cp assets-k8s:/wrapper.exe wrapper.exe

      - name: Build 2019 K8s
        run: |
          docker build -t solarwinds-otel-collector:${{ steps.generate-tag.outputs.tag }}-nanoserver-ltsc2019-k8s --build-arg WINBASE=mcr.microsoft.com/windows/nanoserver:ltsc2019 -f build/docker/Dockerfile.k8s.Windows-Runtime . 
            
      - name: Save image
        run: |
          docker save --output solarwinds-otel-collector-windows-k8s-ltsc2022.tar solarwinds-otel-collector:${{ steps.generate-tag.outputs.tag }}-nanoserver-ltsc2022-k8s
          docker save --output solarwinds-otel-collector-windows-k8s-ltsc2019.tar solarwinds-otel-collector:${{ steps.generate-tag.outputs.tag }}-nanoserver-ltsc2019-k8s
      
      - uses: actions/upload-artifact@v4
        with:
          name: image
          path: |
            solarwinds-otel-collector-windows-k8s-ltsc2022.tar
            solarwinds-otel-collector-windows-k8s-ltsc2019.tar
          retention-days: 2
