name: Build and Test Images

on:
  pull_request:
    branches:
      - main
      - 'release/**'
  push:
    branches:
      - main
      - 'release/**'

  workflow_dispatch:
  workflow_call:

env:
  DOCKERHUB_IMAGE: solarwinds/solarwinds-otel-collector

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check licenses
        run: make ci-check-licenses
      - name: Check that the release version is synced across the repo
        run: |
          make prepare-release version=$(grep -oP '(?<=const Version = ")[^"]+' "./pkg/version/version.go")
          git diff --exit-code

  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: is there
        run: ls /home/runner/work/solarwinds-otel-collector/solarwinds-otel-collector/.github/actions/dockerScoutScan

      - name: Docker scout image scan
        uses: ./.github/actions/dockerScoutScan/action.yml
        with:
          image: solarwinds-otel-collector:${{ steps.generate-tag.outputs.tag }}
          compare-to: solarwinds/solarwinds-otel-collector:latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
          username: ${{ vars.ENOPS5919_DOCKER_SCOUT_CI_USER }}
          token: ${{ secrets.ENOPS5919_DOCKER_SCOUT_CI_PAT }}

      - name: Generate Docker Image Tag
        id: generate-tag
        run: echo "tag=v${{ github.run_number }}-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and Test - Full Image
        run: >
          docker build . --file build/docker/Dockerfile
          --tag solarwinds-otel-collector:${{ steps.generate-tag.outputs.tag }}
          --tag solarwinds-otel-collector:latest

      - name: E2E Tests
        working-directory: internal/e2e
        run: make e2e-tests

      - name: whereami
        run: ls -la

      - name: whereami github
        run: ls ./.github/workflows

      - name: whereami github
        run: ls ./.github/workflows/dockerScoutScan

      - name: Docker scout image scan
        uses: ./.github/actions/dockerScoutScan/action.yml
        with:
          image: solarwinds-otel-collector:${{ steps.generate-tag.outputs.tag }}
          compare-to: solarwinds/solarwinds-otel-collector:latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
          username: ${{ vars.ENOPS5919_DOCKER_SCOUT_CI_USER }}
          token: ${{ secrets.ENOPS5919_DOCKER_SCOUT_CI_PAT }}

  build_windows:
    runs-on: windows-2022
    # this job takes a long time to run (20 minutes), so run it on main and release branches to have some continuous check that build on windows 
    # still works. Also run it on workflow_dispatch to allow manual runs.
    if: github.event_name == 'workflow_call' || github.event_name == 'workflow_dispatch' || github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate docker image tag
        id: generate-tag
        run: echo "tag=v${{ github.run_number }}-$(git rev-parse --short HEAD)" >> $env:GITHUB_OUTPUT

      - name: Build Full
        run: |
          docker build -t solarwinds-otel-collector:${{ steps.generate-tag.outputs.tag }}-nanoserver-ltsc2022 -f build/docker/Dockerfile.Windows-2022 . 

      - name: CP assets
        run: |
          docker create --name assets solarwinds-otel-collector:${{ steps.generate-tag.outputs.tag }}-nanoserver-ltsc2022
          docker cp assets:/solarwinds-otel-collector.exe solarwinds-otel-collector.exe

      - name: Build 2019 Full
        run: |
          docker build -t solarwinds-otel-collector:${{ steps.generate-tag.outputs.tag }}-nanoserver-ltsc2019 --build-arg WINBASE=mcr.microsoft.com/windows/nanoserver:ltsc2019 -f build/docker/Dockerfile.Windows-Runtime . 

      - name: Save image
        if: github.event_name != 'push'
        run: |
          docker save --output solarwinds-otel-collector-windows-ltsc2022.tar solarwinds-otel-collector:${{ steps.generate-tag.outputs.tag }}-nanoserver-ltsc2022
          docker save --output solarwinds-otel-collector-windows-ltsc2019.tar solarwinds-otel-collector:${{ steps.generate-tag.outputs.tag }}-nanoserver-ltsc2019

      - uses: actions/upload-artifact@v4
        if: github.event_name != 'push'
        with:
          name: windows-image-full
          path: |
            solarwinds-otel-collector-windows-ltsc2022.tar
            solarwinds-otel-collector-windows-ltsc2019.tar
          retention-days: 2
 
  build_k8s:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Docker Image Tag
        id: generate-tag
        run: echo "tag=v${{ github.run_number }}-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build - k8s Image
        run: >
          docker build . --file build/docker/Dockerfile.k8s
          --tag solarwinds-otel-collector:${{ steps.generate-tag.outputs.tag }}-k8s

      - name: Log into registry with PAT to use SCOUT.
        uses: docker/login-action@v3
        with:
          username: ${{ vars.ENOPS5919_DOCKER_SCOUT_CI_USER }}
          password: ${{ secrets.ENOPS5919_DOCKER_SCOUT_CI_PAT }}

      - name: Docker scout
        id: docker-scout
        uses: docker/scout-action@v1
        with:
          command: compare
          image: solarwinds-otel-collector:${{ steps.generate-tag.outputs.tag }}-k8s
          to: solarwinds/solarwinds-otel-collector:k8s
          write-comment: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build_windows_k8s:
    runs-on: windows-2022
    # this job takes a long time to run (10 minutes), so run it on main and release branches to have some continuous check that build on windows
    # still works. Also run it on workflow_dispatch to allow manual runs.
    if: github.event_name == 'workflow_call' || github.event_name == 'workflow_dispatch' || github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate docker image tag
        id: generate-tag
        run: echo "tag=v${{ github.run_number }}-$(git rev-parse --short HEAD)" >> $env:GITHUB_OUTPUT

      - name: Build K8s
        run: |
          docker build -t solarwinds-otel-collector:${{ steps.generate-tag.outputs.tag }}-nanoserver-ltsc2022-k8s -f build/docker/Dockerfile.k8s.Windows-2022 . 
          
      - name: CP assets
        run: |
          docker create --name assets-k8s solarwinds-otel-collector:${{ steps.generate-tag.outputs.tag }}-nanoserver-ltsc2022-k8s
          docker cp assets-k8s:/solarwinds-otel-collector.exe solarwinds-otel-collector.exe
          docker cp assets-k8s:/wrapper.exe wrapper.exe

      - name: Build 2019 K8s
        run: |
          docker build -t solarwinds-otel-collector:${{ steps.generate-tag.outputs.tag }}-nanoserver-ltsc2019-k8s --build-arg WINBASE=mcr.microsoft.com/windows/nanoserver:ltsc2019 -f build/docker/Dockerfile.k8s.Windows-Runtime . 
            
      - name: Save image
        if: github.event_name != 'push'
        run: |
          docker save --output solarwinds-otel-collector-windows-k8s-ltsc2022.tar solarwinds-otel-collector:${{ steps.generate-tag.outputs.tag }}-nanoserver-ltsc2022-k8s
          docker save --output solarwinds-otel-collector-windows-k8s-ltsc2019.tar solarwinds-otel-collector:${{ steps.generate-tag.outputs.tag }}-nanoserver-ltsc2019-k8s
      
      - uses: actions/upload-artifact@v4
        if: github.event_name != 'push'
        with:
          name: windows-image-k8s
          path: |
            solarwinds-otel-collector-windows-k8s-ltsc2022.tar
            solarwinds-otel-collector-windows-k8s-ltsc2019.tar
          retention-days: 2
