name: Upload SARIF Files

on:
  workflow_run:
    workflows:
      - Deploy Images
    types:
      - completed

jobs:
  generate-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.generate-tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Docker Image Tag
        id: generate-tag
        run: echo "tag=v${{ github.run_number }}-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

  upload_sarif_files:
    runs-on: ubuntu-latest
    needs: generate-tag
    strategy:
      matrix:
        tag:
          - ${{ needs.generate-tag.outputs.tag }}-nanoserver-ltsc2019
          - ${{ needs.generate-tag.outputs.tag }}-nanoserver-ltsc2022
          - ${{ needs.generate-tag.outputs.tag }}-nanoserver-ltsc2019-k8s
          - ${{ needs.generate-tag.outputs.tag }}-nanoserver-ltsc2022-k8s
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: sarif-${{ matrix.tag }}.output.json

      - name: Upload SARIF results
        id: upload-sarif
        if: ${{ github.event_name != 'pull_request' }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: sarif-${{ matrix.tag }}.output.json
